#!/usr/bin/env bash
# ============================================================
# Alpha (alphaspace-clone) — LAN bootstrap script
# Runs on the Geekom A9. Idempotent — safe to re-run.
#
# What it does:
#   1. Clones (or updates) MarcusWun/alphaspace-clone into ~/apps
#   2. Detects the A9 LAN IP (overridable via A9_LAN_IP env var)
#   3. Generates AUTH_SECRET locally with openssl
#   4. Prompts for the Finnhub API key (no echo)
#   5. Writes .env with all LAN values pre-baked
#   6. chmod 600 .env
#
# What it does NOT do:
#   - Run docker compose up (that's the next step; script tells you the command)
#   - Send anything over the network beyond `git clone`
# ============================================================

set -euo pipefail

APPS_DIR="${APPS_DIR:-$HOME/apps}"
REPO_URL="https://github.com/MarcusWun/alphaspace-clone.git"
REPO_DIR="$APPS_DIR/alphaspace-clone"

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; exit 1; }

# ---- 1. Dependency check --------------------------------------------------
command -v git >/dev/null    || die "git not found — install with: sudo apt-get install -y git"
command -v openssl >/dev/null || die "openssl not found — install with: sudo apt-get install -y openssl"
command -v docker >/dev/null  || warn "docker not found — you'll need it before 'docker compose up'"
docker compose version >/dev/null 2>&1 || warn "docker compose plugin missing — required for the next step"

# ---- 2. Detect LAN IP -----------------------------------------------------
detect_lan_ip() {
  # Pick the source IP the OS would use to reach the internet — that's your LAN address.
  ip route get 1.1.1.1 2>/dev/null | awk '/src/ {for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}'
}

LAN_IP="${A9_LAN_IP:-$(detect_lan_ip)}"
[[ -n "$LAN_IP" ]] || die "Could not detect LAN IP. Re-run with: A9_LAN_IP=192.168.x.x bash $0"
say "LAN IP: $LAN_IP  (override with A9_LAN_IP=... if wrong)"

# ---- 3. Clone or update the repo ------------------------------------------
mkdir -p "$APPS_DIR"
if [[ -d "$REPO_DIR/.git" ]]; then
  say "Repo already present at $REPO_DIR — pulling latest"
  git -C "$REPO_DIR" pull --ff-only
else
  say "Cloning $REPO_URL into $REPO_DIR"
  git clone "$REPO_URL" "$REPO_DIR"
fi
cd "$REPO_DIR"

# ---- 4. Generate AUTH_SECRET ---------------------------------------------
AUTH_SECRET_VALUE="$(openssl rand -base64 32)"
say "Generated fresh AUTH_SECRET (32 bytes, base64)"

# ---- 5. Prompt for Finnhub key -------------------------------------------
if [[ -n "${FINNHUB_API_KEY:-}" ]]; then
  say "Using FINNHUB_API_KEY from environment"
  FINNHUB_VALUE="$FINNHUB_API_KEY"
else
  echo
  echo "Paste your Finnhub API key (input hidden, press Enter when done):"
  read -r -s FINNHUB_VALUE
  echo
  [[ -n "$FINNHUB_VALUE" ]] || die "Empty Finnhub key — aborting."
fi

# ---- 6. Back up any existing .env ----------------------------------------
if [[ -f .env ]]; then
  BACKUP=".env.bak.$(date +%Y%m%d-%H%M%S)"
  cp .env "$BACKUP"
  say "Existing .env backed up to $BACKUP"
fi

# ---- 7. Write .env --------------------------------------------------------
umask 077
cat > .env <<EOF
# ============================================================
# Alpha — LAN deployment .env
# Generated by bootstrap-lan.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# ============================================================

# ---- Finnhub (server-side only) ----
FINNHUB_API_KEY=$FINNHUB_VALUE

# ---- Auth.js v5 — password-only ----
AUTH_SECRET=$AUTH_SECRET_VALUE
AUTH_URL=http://$LAN_IP:3000
AUTH_TRUST_HOST=true

# ---- Email magic-link (disabled) ----
AUTH_EMAIL_SERVER=
AUTH_EMAIL_FROM=

# ---- OAuth providers (disabled) ----
NEXT_PUBLIC_HAS_GITHUB=false
NEXT_PUBLIC_HAS_GOOGLE=false

# ---- API URL for LAN browsers ----
NEXT_PUBLIC_API_URL=http://$LAN_IP:3001

# ---- Rate limiting ----
RATE_LIMIT_MAX=120
RATE_LIMIT_WINDOW_MS=60000
EOF

chmod 600 .env

# ---- 8. Summary -----------------------------------------------------------
echo
say "Done."
echo
echo "  Repo:        $REPO_DIR"
echo "  .env:        $REPO_DIR/.env  (mode $(stat -c '%a' .env))"
echo "  LAN IP:      $LAN_IP"
echo "  Web URL:     http://$LAN_IP:3000"
echo "  API URL:     http://$LAN_IP:3001"
echo
echo "Next step (run from $REPO_DIR):"
echo
echo "    docker compose up -d --build"
echo
echo "Then watch logs with:  docker compose logs -f"
echo
